version: "3"

services:
  languagetool:
    image: erikvl87/languagetool
    ports:
      - 172.17.0.1:8010:8081                        # Using default port from the image
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - Java_Xms=512m                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ./data:/ngrams     # OPTIONAL: The location of ngrams data on the local machine